// ============================================================================
// PRODUCTION-READY Scan Export Service
// Converts point cloud data to standard 3D formats (OBJ, PLY, XYZ, CSV)
//
// Features:
//   • OBJ export with vertex colors
//   • PLY export (binary + ASCII) with confidence data
//   • XYZ plain text export
//   • CSV export for spreadsheet analysis
//   • Metadata JSON sidecar
//   • Share via system share sheet (share_plus)
//   • File size estimation
//
// NO backend dependency — all exports are local-only
// ============================================================================
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui' show Rect, Offset;
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart' show RenderBox;
import 'package:flutter/widgets.dart' show BuildContext;
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/scan_point_model.dart';
import 'local_scan_storage_service.dart';

enum ExportFormat { obj, ply, xyz, csv, json }

class ExportResult {
  final String filePath;
  final ExportFormat format;
  final int fileSize;
  final int pointCount;
  final Duration exportDuration;

  ExportResult({
    required this.filePath,
    required this.format,
    required this.fileSize,
    required this.pointCount,
    required this.exportDuration,
  });

  String get fileSizeFormatted {
    if (fileSize < 1024) return '$fileSize B';
    if (fileSize < 1024 * 1024) return '${(fileSize / 1024).toStringAsFixed(1)} KB';
    return '${(fileSize / (1024 * 1024)).toStringAsFixed(1)} MB';
  }
}

class ScanExportService {
  static ScanExportService? _instance;
  static ScanExportService get instance {
    _instance ??= ScanExportService._();
    return _instance!;
  }

  ScanExportService._();

  Directory? _exportDir;

  Future<Directory> _getExportDir() async {
    if (_exportDir != null) return _exportDir!;
    final appDir = await getApplicationDocumentsDirectory();
    _exportDir = Directory(p.join(appDir.path, 'exports'));
    if (!_exportDir!.existsSync()) {
      _exportDir!.createSync(recursive: true);
    }
    return _exportDir!;
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EXPORT TO OBJ FORMAT
  // Wavefront OBJ — widely supported by all 3D software
  // ══════════════════════════════════════════════════════════════════════════

  Future<ExportResult> exportToOBJ({
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
    ScanSession? session,
  }) async {
    final sw = Stopwatch()..start();
    final dir = await _getExportDir();
    final safeName = _sanitizeFilename(scanName);
    final filePath = p.join(dir.path, '${safeName}_$sessionId.obj');

    final buffer = StringBuffer();

    // OBJ Header
    buffer.writeln('# LiDAR Pro Scanner — OBJ Export');
    buffer.writeln('# Scan: $scanName');
    buffer.writeln('# Points: ${points.length}');
    buffer.writeln('# Date: ${DateTime.now().toIso8601String()}');
    if (session != null) {
      buffer.writeln('# Quality: ${(session.qualityScore * 100).toInt()}%');
      buffer.writeln('# Coverage: ${session.coveragePercent.toInt()}%');
      buffer.writeln('# Device: ${session.deviceModel} (${session.deviceType})');
    }
    buffer.writeln('# Generated by LiDAR Pro Scanner App');
    buffer.writeln();
    buffer.writeln('o $safeName');
    buffer.writeln();

    // Vertices with vertex colors (OBJ extension)
    for (final pt in points) {
      // Color based on confidence: high=green, medium=yellow, low=red
      final r = pt.confidence < 0.5 ? 1.0 : (1.0 - pt.confidence) * 2.0;
      final g = pt.confidence > 0.5 ? 1.0 : pt.confidence * 2.0;
      final b = 0.2;
      buffer.writeln(
        'v ${pt.x.toStringAsFixed(6)} ${pt.y.toStringAsFixed(6)} ${pt.z.toStringAsFixed(6)} '
        '${r.toStringAsFixed(3)} ${g.toStringAsFixed(3)} ${b.toStringAsFixed(3)}'
      );
    }

    buffer.writeln();
    buffer.writeln('# Point cloud — no faces');

    // Write file
    final file = File(filePath);
    await file.writeAsString(buffer.toString());

    sw.stop();
    debugPrint('📦 [Export] OBJ exported: ${points.length} pts → ${file.lengthSync()} bytes');

    return ExportResult(
      filePath: filePath,
      format: ExportFormat.obj,
      fileSize: file.lengthSync(),
      pointCount: points.length,
      exportDuration: sw.elapsed,
    );
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EXPORT TO PLY FORMAT
  // Stanford PLY — supports vertex properties natively
  // ══════════════════════════════════════════════════════════════════════════

  Future<ExportResult> exportToPLY({
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
    ScanSession? session,
  }) async {
    final sw = Stopwatch()..start();
    final dir = await _getExportDir();
    final safeName = _sanitizeFilename(scanName);
    final filePath = p.join(dir.path, '${safeName}_$sessionId.ply');

    final buffer = StringBuffer();

    // PLY Header (ASCII format for maximum compatibility)
    buffer.writeln('ply');
    buffer.writeln('format ascii 1.0');
    buffer.writeln('comment LiDAR Pro Scanner — PLY Export');
    buffer.writeln('comment Scan: $scanName');
    buffer.writeln('comment Date: ${DateTime.now().toIso8601String()}');
    if (session != null) {
      buffer.writeln('comment Quality: ${(session.qualityScore * 100).toInt()}%');
      buffer.writeln('comment Device: ${session.deviceModel}');
    }
    buffer.writeln('element vertex ${points.length}');
    buffer.writeln('property float x');
    buffer.writeln('property float y');
    buffer.writeln('property float z');
    buffer.writeln('property float confidence');
    buffer.writeln('property uchar red');
    buffer.writeln('property uchar green');
    buffer.writeln('property uchar blue');
    buffer.writeln('property int sequence');
    buffer.writeln('property uchar is_manual_pin');
    buffer.writeln('end_header');

    // Vertex data
    for (final pt in points) {
      // Color by confidence
      final r = (pt.confidence < 0.5 ? 255 : ((1.0 - pt.confidence) * 2.0 * 255).toInt()).clamp(0, 255);
      final g = (pt.confidence > 0.5 ? 255 : (pt.confidence * 2.0 * 255).toInt()).clamp(0, 255);
      const b = 50;

      buffer.writeln(
        '${pt.x.toStringAsFixed(6)} ${pt.y.toStringAsFixed(6)} ${pt.z.toStringAsFixed(6)} '
        '${pt.confidence.toStringAsFixed(4)} $r $g $b '
        '${pt.sequenceNumber} ${pt.isManualPin ? 1 : 0}'
      );
    }

    final file = File(filePath);
    await file.writeAsString(buffer.toString());

    sw.stop();
    debugPrint('📦 [Export] PLY exported: ${points.length} pts → ${file.lengthSync()} bytes');

    return ExportResult(
      filePath: filePath,
      format: ExportFormat.ply,
      fileSize: file.lengthSync(),
      pointCount: points.length,
      exportDuration: sw.elapsed,
    );
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EXPORT TO XYZ FORMAT
  // Simple text — one point per line (x y z)
  // ══════════════════════════════════════════════════════════════════════════

  Future<ExportResult> exportToXYZ({
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
  }) async {
    final sw = Stopwatch()..start();
    final dir = await _getExportDir();
    final safeName = _sanitizeFilename(scanName);
    final filePath = p.join(dir.path, '${safeName}_$sessionId.xyz');

    final buffer = StringBuffer();
    for (final pt in points) {
      buffer.writeln('${pt.x.toStringAsFixed(6)} ${pt.y.toStringAsFixed(6)} ${pt.z.toStringAsFixed(6)}');
    }

    final file = File(filePath);
    await file.writeAsString(buffer.toString());

    sw.stop();
    return ExportResult(
      filePath: filePath,
      format: ExportFormat.xyz,
      fileSize: file.lengthSync(),
      pointCount: points.length,
      exportDuration: sw.elapsed,
    );
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EXPORT TO CSV FORMAT
  // Spreadsheet-friendly with all point properties
  // ══════════════════════════════════════════════════════════════════════════

  Future<ExportResult> exportToCSV({
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
  }) async {
    final sw = Stopwatch()..start();
    final dir = await _getExportDir();
    final safeName = _sanitizeFilename(scanName);
    final filePath = p.join(dir.path, '${safeName}_$sessionId.csv');

    final buffer = StringBuffer();
    buffer.writeln('x,y,z,confidence,sequence_number,is_manual_pin');
    for (final pt in points) {
      buffer.writeln(
        '${pt.x.toStringAsFixed(6)},${pt.y.toStringAsFixed(6)},${pt.z.toStringAsFixed(6)},'
        '${pt.confidence.toStringAsFixed(4)},${pt.sequenceNumber},${pt.isManualPin ? 1 : 0}'
      );
    }

    final file = File(filePath);
    await file.writeAsString(buffer.toString());

    sw.stop();
    return ExportResult(
      filePath: filePath,
      format: ExportFormat.csv,
      fileSize: file.lengthSync(),
      pointCount: points.length,
      exportDuration: sw.elapsed,
    );
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EXPORT METADATA JSON
  // Full scan metadata as sidecar file
  // ══════════════════════════════════════════════════════════════════════════

  Future<ExportResult> exportMetadataJSON({
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
    required ScanSession session,
  }) async {
    final sw = Stopwatch()..start();
    final dir = await _getExportDir();
    final safeName = _sanitizeFilename(scanName);
    final filePath = p.join(dir.path, '${safeName}_$sessionId.json');

    final metadata = {
      'scanId': session.id,
      'name': session.name,
      'roomType': session.roomType,
      'createdAt': session.createdAt.toIso8601String(),
      'completedAt': session.completedAt?.toIso8601String(),
      'status': session.status.name,
      'pointCount': session.pointCount,
      'manualPinCount': session.manualPinCount,
      'qualityScore': session.qualityScore,
      'coveragePercent': session.coveragePercent,
      'stabilityScore': session.stabilityScore,
      'durationSeconds': session.durationSeconds,
      'deviceType': session.deviceType,
      'deviceModel': session.deviceModel,
      'metadata': session.metadata,
      'segments': session.segments?.map((s) => s.toMap()).toList(),
      'exportInfo': {
        'exportedAt': DateTime.now().toIso8601String(),
        'exportedBy': 'LiDAR Pro Scanner App',
        'version': '1.0.0',
      },
      'boundingBox': _calculateBoundingBox(points),
    };

    final file = File(filePath);
    final encoder = const JsonEncoder.withIndent('  ');
    await file.writeAsString(encoder.convert(metadata));

    sw.stop();
    return ExportResult(
      filePath: filePath,
      format: ExportFormat.json,
      fileSize: file.lengthSync(),
      pointCount: points.length,
      exportDuration: sw.elapsed,
    );
  }

  /// Compute share origin rect from BuildContext (required on iOS for popover anchor)
  static Rect? getShareOrigin(BuildContext context) {
    final renderBox = context.findRenderObject() as RenderBox?;
    if (renderBox == null || !renderBox.hasSize) return null;
    return renderBox.localToGlobal(Offset.zero) & renderBox.size;
  }

  // ══════════════════════════════════════════════════════════════════════════
  // SHARE EXPORTED FILE
  // Uses system share sheet via share_plus
  // ══════════════════════════════════════════════════════════════════════════

  Future<void> shareFile(String filePath, {String? subject, Rect? sharePositionOrigin}) async {
    final file = XFile(filePath);
    await Share.shareXFiles(
      [file],
      subject: subject ?? 'LiDAR Scan Export',
      text: 'Exported from LiDAR Pro Scanner',
      sharePositionOrigin: sharePositionOrigin,
    );
  }

  /// Export and immediately share
  Future<ExportResult> exportAndShare({
    required ExportFormat format,
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
    ScanSession? session,
    Rect? sharePositionOrigin,
  }) async {
    final result = await _exportByFormat(
      format: format,
      sessionId: sessionId,
      scanName: scanName,
      points: points,
      session: session,
    );

    await shareFile(result.filePath, subject: 'LiDAR Scan: $scanName', sharePositionOrigin: sharePositionOrigin);
    return result;
  }

  /// Export to all formats and share as bundle
  Future<List<ExportResult>> exportBundle({
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
    required ScanSession session,
    Rect? sharePositionOrigin,
  }) async {
    final results = <ExportResult>[];

    results.add(await exportToOBJ(
      sessionId: sessionId, scanName: scanName, points: points, session: session,
    ));
    results.add(await exportToPLY(
      sessionId: sessionId, scanName: scanName, points: points, session: session,
    ));
    results.add(await exportMetadataJSON(
      sessionId: sessionId, scanName: scanName, points: points, session: session,
    ));

    // Share all files
    final files = results.map((r) => XFile(r.filePath)).toList();
    await Share.shareXFiles(
      files,
      subject: 'LiDAR Scan Bundle: $scanName',
      text: 'Exported from LiDAR Pro Scanner (OBJ + PLY + Metadata)',
      sharePositionOrigin: sharePositionOrigin,
    );

    return results;
  }

  // ══════════════════════════════════════════════════════════════════════════
  // ESTIMATE FILE SIZE
  // ══════════════════════════════════════════════════════════════════════════

  /// Estimate export file size (bytes) without actually exporting
  int estimateFileSize(ExportFormat format, int pointCount) {
    switch (format) {
      case ExportFormat.obj:
        return pointCount * 65; // ~65 bytes per vertex line
      case ExportFormat.ply:
        return 200 + pointCount * 55; // header + ~55 bytes per vertex
      case ExportFormat.xyz:
        return pointCount * 35; // ~35 bytes per line
      case ExportFormat.csv:
        return 60 + pointCount * 50; // header + ~50 bytes per line
      case ExportFormat.json:
        return 2000; // metadata only, small
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // CLEANUP OLD EXPORTS
  // ══════════════════════════════════════════════════════════════════════════

  Future<int> cleanupOldExports({Duration maxAge = const Duration(days: 7)}) async {
    final dir = await _getExportDir();
    if (!dir.existsSync()) return 0;

    int deleted = 0;
    final cutoff = DateTime.now().subtract(maxAge);

    await for (final entity in dir.list()) {
      if (entity is File) {
        final stat = await entity.stat();
        if (stat.modified.isBefore(cutoff)) {
          await entity.delete();
          deleted++;
        }
      }
    }

    debugPrint('🧹 [Export] Cleaned up $deleted old export files');
    return deleted;
  }

  // ── Private Helpers ────────────────────────────────────────────────────

  Future<ExportResult> _exportByFormat({
    required ExportFormat format,
    required String sessionId,
    required String scanName,
    required List<ScanPoint> points,
    ScanSession? session,
  }) async {
    switch (format) {
      case ExportFormat.obj:
        return exportToOBJ(sessionId: sessionId, scanName: scanName, points: points, session: session);
      case ExportFormat.ply:
        return exportToPLY(sessionId: sessionId, scanName: scanName, points: points, session: session);
      case ExportFormat.xyz:
        return exportToXYZ(sessionId: sessionId, scanName: scanName, points: points);
      case ExportFormat.csv:
        return exportToCSV(sessionId: sessionId, scanName: scanName, points: points);
      case ExportFormat.json:
        if (session == null) throw Exception('Session required for JSON export');
        return exportMetadataJSON(sessionId: sessionId, scanName: scanName, points: points, session: session);
    }
  }

  String _sanitizeFilename(String name) {
    return name
        .replaceAll(RegExp(r'[^\w\s\-]'), '')
        .replaceAll(RegExp(r'\s+'), '_')
        .toLowerCase();
  }

  Map<String, dynamic> _calculateBoundingBox(List<ScanPoint> points) {
    if (points.isEmpty) {
      return {'minX': 0, 'minY': 0, 'minZ': 0, 'maxX': 0, 'maxY': 0, 'maxZ': 0};
    }
    double minX = double.infinity, minY = double.infinity, minZ = double.infinity;
    double maxX = double.negativeInfinity, maxY = double.negativeInfinity, maxZ = double.negativeInfinity;
    for (final pt in points) {
      if (pt.x < minX) minX = pt.x;
      if (pt.y < minY) minY = pt.y;
      if (pt.z < minZ) minZ = pt.z;
      if (pt.x > maxX) maxX = pt.x;
      if (pt.y > maxY) maxY = pt.y;
      if (pt.z > maxZ) maxZ = pt.z;
    }
    return {
      'minX': minX, 'minY': minY, 'minZ': minZ,
      'maxX': maxX, 'maxY': maxY, 'maxZ': maxZ,
      'sizeX': maxX - minX, 'sizeY': maxY - minY, 'sizeZ': maxZ - minZ,
    };
  }
}
